%% FOME Simulink Code Generation Target
% Generates C code from Simulink models for FOME ECU integration
%
% Usage:
%   fome_codegen('my_controller.slx', 'output_dir')
%
% This script configures Simulink Coder for embedded targets
% compatible with the FOME vehicle profile system.

function fome_codegen(model_name, output_dir)
    %% Validate inputs
    if nargin < 1
        error('Model name required');
    end
    if nargin < 2
        output_dir = 'generated_code';
    end

    %% Load model
    [~, model_base, ~] = fileparts(model_name);
    load_system(model_name);

    %% Configure code generation settings
    fprintf('Configuring code generation for FOME...\n');

    % Set target configuration
    set_param(model_base, 'SystemTargetFile', 'ert.tlc');
    set_param(model_base, 'TargetLang', 'C');
    set_param(model_base, 'GenCodeOnly', 'on');

    % Code generation options
    set_param(model_base, 'GenerateReport', 'on');
    set_param(model_base, 'LaunchReport', 'off');
    set_param(model_base, 'RTWVerbose', 'off');

    % Data type settings for embedded
    set_param(model_base, 'DefaultUnderspecifiedDataType', 'single');
    set_param(model_base, 'DataTypeOverride', 'UseLocalSettings');

    % Memory optimization
    set_param(model_base, 'OptimizeBlockIOStorage', 'on');
    set_param(model_base, 'LocalBlockOutputs', 'on');
    set_param(model_base, 'BufferReuse', 'on');

    % Interface settings for FOME
    set_param(model_base, 'SupportNonFinite', 'off');
    set_param(model_base, 'SupportComplex', 'off');
    set_param(model_base, 'SupportAbsoluteTime', 'off');
    set_param(model_base, 'SupportContinuousTime', 'off');

    % Generate reusable code
    set_param(model_base, 'MultiInstanceERTCode', 'on');
    set_param(model_base, 'RootIOFormat', 'Structure reference');

    % MISRA-C compliance (automotive standard)
    set_param(model_base, 'EnableUserReplacementTypes', 'on');

    %% Set output directory
    if ~exist(output_dir, 'dir')
        mkdir(output_dir);
    end
    set_param(model_base, 'CodeGenFolder', output_dir);

    %% Generate code
    fprintf('Generating code for model: %s\n', model_base);
    try
        slbuild(model_base);
        fprintf('Code generation complete!\n');
        fprintf('Output directory: %s\n', fullfile(output_dir, [model_base '_ert_rtw']));
    catch ME
        fprintf('Code generation failed: %s\n', ME.message);
        rethrow(ME);
    end

    %% Generate FOME integration wrapper
    generate_fome_wrapper(model_base, output_dir);

    %% Close model
    close_system(model_base, 0);
end

function generate_fome_wrapper(model_base, output_dir)
    %% Generate wrapper code for FOME integration
    wrapper_file = fullfile(output_dir, [model_base '_fome_wrapper.cpp']);

    fid = fopen(wrapper_file, 'w');
    if fid == -1
        error('Cannot create wrapper file');
    end

    fprintf(fid, '/*\n');
    fprintf(fid, ' * FOME Integration Wrapper for %s\n', model_base);
    fprintf(fid, ' * Auto-generated by fome_codegen.m\n');
    fprintf(fid, ' */\n\n');

    fprintf(fid, '#include "%s.h"\n', model_base);
    fprintf(fid, '#include "../vehicle_profiles/vehicle_profile.h"\n');
    fprintf(fid, '#include "../xcp/xcp_protocol.h"\n\n');

    fprintf(fid, '// Model instance\n');
    fprintf(fid, 'static %s_ModelClass model;\n\n', model_base);

    fprintf(fid, '// Initialize model\n');
    fprintf(fid, 'void %s_fome_init(void) {\n', model_base);
    fprintf(fid, '    model.initialize();\n');
    fprintf(fid, '}\n\n');

    fprintf(fid, '// Step model (call from FOME main loop)\n');
    fprintf(fid, 'void %s_fome_step(void) {\n', model_base);
    fprintf(fid, '    model.step();\n');
    fprintf(fid, '}\n\n');

    fprintf(fid, '// Get model outputs for XCP\n');
    fprintf(fid, 'void* %s_get_outputs(void) {\n', model_base);
    fprintf(fid, '    return (void*)&model.getExternalOutputs();\n');
    fprintf(fid, '}\n\n');

    fprintf(fid, '// Set model inputs from sensors\n');
    fprintf(fid, 'void %s_set_inputs(void* inputs) {\n', model_base);
    fprintf(fid, '    // Copy sensor data to model inputs\n');
    fprintf(fid, '    // Implementation depends on model interface\n');
    fprintf(fid, '}\n');

    fclose(fid);

    fprintf('Generated FOME wrapper: %s\n', wrapper_file);
end

%% Example model configuration
function create_example_model()
    % Create a simple example model for testing
    model_name = 'fome_controller_example';

    new_system(model_name);
    open_system(model_name);

    % Add input port (throttle)
    add_block('simulink/Sources/In1', [model_name '/Throttle']);
    set_param([model_name '/Throttle'], 'Position', [50 100 80 114]);

    % Add gain block (throttle mapping)
    add_block('simulink/Math Operations/Gain', [model_name '/ThrottleGain']);
    set_param([model_name '/ThrottleGain'], 'Gain', '1.5');
    set_param([model_name '/ThrottleGain'], 'Position', [150 95 180 125]);

    % Add saturation (limit output)
    add_block('simulink/Discontinuities/Saturation', [model_name '/Saturation']);
    set_param([model_name '/Saturation'], 'UpperLimit', '100');
    set_param([model_name '/Saturation'], 'LowerLimit', '0');
    set_param([model_name '/Saturation'], 'Position', [250 95 280 125]);

    % Add output port
    add_block('simulink/Sinks/Out1', [model_name '/FuelPulseWidth']);
    set_param([model_name '/FuelPulseWidth'], 'Position', [350 100 380 114]);

    % Connect blocks
    add_line(model_name, 'Throttle/1', 'ThrottleGain/1');
    add_line(model_name, 'ThrottleGain/1', 'Saturation/1');
    add_line(model_name, 'Saturation/1', 'FuelPulseWidth/1');

    % Save model
    save_system(model_name);
    close_system(model_name);

    fprintf('Created example model: %s.slx\n', model_name);
end
